version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-architecture
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - 9229:9229
    networks:
      - architecture-network
  db:
    image: postgres
    container_name: architecture-db
    tty: true
    environment:
      - POSTGRES_DB=architecture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - architecture-pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - architecture-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: architecture-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_HOST=db
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '9000:80'
    networks:
      - architecture-network
    depends_on:
      - db

networks:
  architecture-network:
    driver: bridge
    external: true

volumes:
  architecture-pgdata:
    external: true
