version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcc-api
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 3000:3000
      - 9229:9229
    expose: 
      - 3000
      - 9229
    networks:
      - tcc-network
  db:
    image: postgres
    container_name: tcc-db
    tty: true
    environment:
      - POSTGRES_DB=tcc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - tcc-pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - tcc-network

networks:
  tcc-network:
    driver: bridge
    external: true

volumes:
  tcc-pgdata:
    external: true
